name: gitlab-ci

on:
  workflow_dispatch: # Allows manual triggering
  pull_request:
    types: [opened, synchronize] # Trigger on PR events
  push:
    branches:
      - main

jobs:
  gitlab-ci:
    runs-on: ubuntu-latest
    steps:
      - name: Print Secret
        run: |
          [ "${{ secrets.THEANSWER }}" -eq 42 ] || exit 1
        